name: "💡 Enhancement request"
description: Propose a new feature or an improvement
labels:
- enhancement
body:
- type: dropdown
  id: kind
  attributes:
    label: What kind of feature would you like to request?
    options:
    - 'New data processing / filtering / wrangling methods you are missing'
    - 'Request enhancement to input/output, e.g., reading data, writing the on the disk'
    - 'Improve existing functions, e.g., additional function parameters / changed functionality / changed defaults'
    - 'Other - please describe it in the ticket body'
  validations:
    required: true
- type: textarea
  id: description
  attributes:
    label: Please describe your idea or what you want to achieve
  validations:
    required: true
