name: "❓ Question"
description: Ask us anything about immundata - how to use it, how to do something, how it works
label: question
- type: textarea
  id: description
  attributes:
    label: Question
    description: Describe what you want to know.
  validations:
    required: true
