#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @import rlang
#' @importFrom checkmate assert
#' @importFrom checkmate assert_character
#' @importFrom checkmate assert_choice
#' @importFrom checkmate assert_class
#' @importFrom checkmate assert_data_frame
#' @importFrom checkmate assert_directory_exists
#' @importFrom checkmate assert_file_exists
#' @importFrom checkmate assert_logical
#' @importFrom checkmate assertCharacter
#' @importFrom checkmate assertR6
#' @importFrom checkmate check_character
#' @importFrom checkmate check_choice
#' @importFrom checkmate check_class
#' @importFrom checkmate check_data_frame
#' @importFrom checkmate check_function
#' @importFrom checkmate check_list
#' @importFrom checkmate check_scalar_na
#' @importFrom checkmate checkCharacter
#' @importFrom checkmate checkChoice
#' @importFrom checkmate checkR6
#' @importFrom checkmate makeAssertion
#' @importFrom checkmate test_character
#' @importFrom checkmate test_data_frame
#' @importFrom checkmate test_file_exists
#' @importFrom checkmate test_function
#' @importFrom checkmate test_list
#' @importFrom cli cli_abort
#' @importFrom cli cli_alert_danger
#' @importFrom cli cli_alert_info
#' @importFrom cli cli_alert_success
#' @importFrom cli cli_alert_warning
#' @importFrom cli cli_end
#' @importFrom cli cli_li
#' @importFrom cli cli_ol
#' @importFrom cli cli_ul
#' @importFrom dplyr all_of
#' @importFrom dplyr any_of
#' @importFrom dplyr collect
#' @importFrom dplyr compute
#' @importFrom dplyr filter
#' @importFrom dplyr full_join
#' @importFrom dplyr n
#' @importFrom dplyr relocate
#' @importFrom dplyr rename
#' @importFrom dplyr right_join
#' @importFrom dplyr row_number
#' @importFrom dplyr select
#' @importFrom dplyr semi_join
#' @importFrom dplyr summarise
#' @importFrom duckplyr as_duckdb_tibble
#' @importFrom duckplyr as_tbl
#' @importFrom duckplyr compute_parquet
#' @importFrom duckplyr duckdb_tibble
#' @importFrom duckplyr read_csv_duckdb
#' @importFrom duckplyr read_parquet_duckdb
#' @importFrom ggplot2 autoplot
#' @importFrom glue glue
#' @importFrom lifecycle deprecated
#' @importFrom R6 R6Class
#' @importFrom readr read_delim
#' @importFrom rlang sym
#' @importFrom rlang syms
#' @importFrom tibble as_tibble
#' @importFrom tools file_ext
#' @importFrom utils packageDescription
#' @importFrom utils packageVersion
#' @importFrom utils tail
## usethis namespace: end
NULL
